### PR TITLE
feat: DIA-1402: V1-Submit Prompt auto-refinement job

### PR DESCRIPTION
**Pull request by matt-bernstein**
Plan for autorefinement:
```
# this PR - DIA-1402/1407
# makes a single api call to the teacher model and returns the new prompt version immediately
# can extend in future to update the current prompt version using PATCH instead of POST
# other parameters: teacher model provider connection id, teacher model name, project id
/api/prompts/{id}/versions/{version_id}/refine-prompt

# autorefinement using ground truth data
# creates a new "run" object analogous to an InferenceRun, the new or updated prompt version and new inference runs are available when the RefinementRun completes
# same parameters: teacher model provider connection id, teacher model name, project id
# manage state the same way as with InferenceRuns using polling, or try something new like websockets?
/api/prompts/{id}/versions/{version_id}/refinement-runs/{run_id}

# create a prompt version with the "prompt" field already filled in
# extend existing create endpoint
# parameters: optional[teacher model provider connection id, teacher model name], optional[project id]
# if teacher provided, ask it for a good prompt given the skill
# if project id provided, enrich the teacher info with example tasks from the project
# if optional params not provided, "prompt" field can still be null - fallback to a generic string template using skill name and input fields
POST /api/prompts/{id}/versions/
```

### CODE REVIEW

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed. 
> [Workflow run](https://github.com/HumanSignal/label-studio-sdk/actions/runs/11041232536)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed. 
> [Workflow run](https://github.com/HumanSignal/label-studio-sdk/actions/runs/11041232536)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed. 
> [Workflow run](https://github.com/HumanSignal/label-studio-sdk/actions/runs/11041324126)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed. 
> [Workflow run](https://github.com/HumanSignal/label-studio-sdk/actions/runs/11041232536)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed. 
> [Workflow run](https://github.com/HumanSignal/label-studio-sdk/actions/runs/11041232536)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed. 
> [Workflow run](https://github.com/HumanSignal/label-studio-sdk/actions/runs/11041365368)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed. 
> [Workflow run](https://github.com/HumanSignal/label-studio-sdk/actions/runs/11041365368)

**Review by hakan458 — APPROVED** [review]

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed. 
> [Workflow run](https://github.com/HumanSignal/label-studio-sdk/actions/runs/11130911873)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed. 
> [Workflow run](https://github.com/HumanSignal/label-studio-sdk/actions/runs/11132211983)

**Comment by robot-ci-heartex** [comment]
Follow Merge downstream workflow has been failed. 
> [Workflow run](https://github.com/HumanSignal/label-studio-sdk/actions/runs/11134825113)

**Pull request merged**
